### ISSUE TITLE
Problem parsing suffix with a dash

### ISSUE THREAD

**Issue by OSUblake** [tristanMatthias/wc-sass-render#1]
First, thanks for making this! This is so much better than having to deal with a webpack build. 😀

I'm having trouble using a suffix with a dash. 

`--suffix '-css.ts'` creates `button'-css.ts'`

`--suffix \"-css.ts\"` creates `button`

It looks like this might be an issue with yargs https://github.com/yargs/yargs/issues/360

**Comment by dastein1** [comment]
@tristanMatthias That PR got merged; Could you bump the yargs dep or should I go ahead and create a PR?

**Comment by pishonx** [comment]
great contribution @tristanMatthias thanks a lot! I also ran into this issue it seems to be an old one.  Are you still maintaining the project or shall I create a PR as @dastein1 first suggested.   Cheers!

**Comment by tristanMatthias** [comment]
Ok thanks for the patience @OSUblake @dastein1 @dastein1 , this is now upgraded.

Please note, you will still need to escape it with `\"`. 
EG: `sass-render --suffix \"-css.ts\"`

Hope that helps!
